using ProjectEulerDesktop;
using System;
using static ProjectEulerDesktop.BaseEulerProblem;

public class Problem2 : BaseEulerProblem
{
    public Problem2()
    {
    }

    /*  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */

    public long EvenFibonacciNumbers(long maxNumber)
    {
		long sum = 10;
		long previous = 8;
		long current = 13;
		for (long x = current; current < maxNumber; x = current + previous, previous = current, current = x)
		{
			if (x % 2 == 0)
			{
				sum += x;
			}
		}

		return sum;
    }
}